### ISSUE TITLE
Subsection-Error

### ISSUE THREAD

**Issue by florianproske** [hollesse/Report-Template#10]
Check if integration of /subsection{title} (in content) dues to the following error:

Undefined control sequence. \subsection{title}

This error depends on the activation of db fonts.

TY

**Comment by florianproske** [comment]
Layout.tex, line 213:
`\addtokomafont{subsection}{\**dbheadbalck**\large\color{SecondaryAccentColor}}`

TYPO

**Comment by LucaVazz** [comment]
Oh, you were quicker.... :disappointed:

**Comment by hollesse** [comment]
Trank you
